spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data-sql 설정
    defer-datasource-initialization: ture

  datasource: # 데이터베이스 정보 추가
    url: jdbc:h2:mem:testdb
    username: sa
  h2: # H2 콘솔 활성화
    console:
      enabled: true

jwt:
  issuer: "yena@gmail.com"
  secret_key: study-springboot